// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/estimate-yield.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";
var locations = {
  praha1: { label: "Praha 1", multiplier: 1.45, occupancy: 0.85 },
  praha2: { label: "Praha 2", multiplier: 1.25, occupancy: 0.83 },
  praha3: { label: "Praha 3", multiplier: 1.05, occupancy: 0.8 },
  praha4: { label: "Praha 4", multiplier: 0.8, occupancy: 0.72 },
  praha5: { label: "Praha 5", multiplier: 1, occupancy: 0.78 },
  praha6: { label: "Praha 6", multiplier: 0.95, occupancy: 0.76 },
  praha7: { label: "Praha 7", multiplier: 1.15, occupancy: 0.83 },
  praha8: { label: "Praha 8", multiplier: 0.85, occupancy: 0.74 },
  praha9: { label: "Praha 9", multiplier: 0.7, occupancy: 0.68 },
  praha10: { label: "Praha 10", multiplier: 0.8, occupancy: 0.73 }
};
var sizes = {
  "1kk": { label: "1+kk", baseADR: 1665 },
  "2kk": { label: "2+kk", baseADR: 2250 },
  "3kk": { label: "3+kk", baseADR: 3060 },
  "4kk": { label: "4+kk", baseADR: 4140 }
};
var extras = {
  balkon: 0.04,
  parking: 0.05,
  klima: 0.03,
  vyhled: 0.08,
  vybaveni: 0.06,
  wellness: 0.05
};
var seasons = {
  year: { adr: 1.05, occDelta: 0.02 },
  summer: { adr: 1.33, occDelta: 0.08 },
  winter: { adr: 0.88, occDelta: 0.05 },
  xmas: { adr: 1.75, occDelta: 0.12 }
};
var ltrTable = {
  praha1: { "1kk": 22e3, "2kk": 32e3, "3kk": 45e3, "4kk": 62e3 },
  praha2: { "1kk": 19e3, "2kk": 28e3, "3kk": 38e3, "4kk": 52e3 },
  praha3: { "1kk": 17e3, "2kk": 24e3, "3kk": 32e3, "4kk": 44e3 },
  praha4: { "1kk": 15e3, "2kk": 21e3, "3kk": 28e3, "4kk": 38e3 },
  praha5: { "1kk": 16500, "2kk": 23e3, "3kk": 31e3, "4kk": 42e3 },
  praha6: { "1kk": 17500, "2kk": 25e3, "3kk": 34e3, "4kk": 46e3 },
  praha7: { "1kk": 17500, "2kk": 25e3, "3kk": 34e3, "4kk": 46e3 },
  praha8: { "1kk": 14500, "2kk": 2e4, "3kk": 27e3, "4kk": 36e3 },
  praha9: { "1kk": 13e3, "2kk": 18e3, "3kk": 24e3, "4kk": 32e3 },
  praha10: { "1kk": 14e3, "2kk": 19500, "3kk": 26e3, "4kk": 35e3 }
};
var MGMT_FEE = 0.25;
var DAYS = 30;
var estimate_yield_default = defineTool({
  name: "estimate_rental_yield",
  title: "Estimate short-term rental yield",
  description: "Estimate the monthly net income an apartment owner in Prague could earn with antam homes short-term rental management, and compare it to long-term rent. Same model as the calculator on the website.",
  inputSchema: {
    location: z.enum(["praha1", "praha2", "praha3", "praha4", "praha5", "praha6", "praha7", "praha8", "praha9", "praha10"]).describe("Prague district of the apartment."),
    size: z.enum(["1kk", "2kk", "3kk", "4kk"]).describe("Apartment layout size."),
    season: z.enum(["year", "summer", "winter", "xmas"]).optional().describe("Season to price for. Defaults to 'year' (yearly average)."),
    extras: z.array(z.enum(["balkon", "parking", "klima", "vyhled", "vybaveni", "wellness"])).optional().describe("Extra features that raise the nightly rate.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ location, size, season, extras: chosen }) => {
    const loc = locations[location];
    const sz = sizes[size];
    if (!loc || !sz) throw new ToolError("Unknown location or size.");
    const extrasPct = (chosen ?? []).reduce((sum, e) => sum + (extras[e] ?? 0), 0);
    const compute = (seasonKey2) => {
      const adj = seasons[seasonKey2];
      const adr = Math.round(sz.baseADR * loc.multiplier * (1 + extrasPct) * adj.adr);
      const occupancy = Math.max(0.5, Math.min(0.98, loc.occupancy + adj.occDelta));
      const gross = Math.round(adr * occupancy * DAYS);
      const commission = Math.round(gross * MGMT_FEE);
      return { adr, occupancy, gross, commission, net: gross - commission };
    };
    const seasonKey = season ?? "year";
    const r = compute(seasonKey);
    const yearly = compute("year");
    const longTermRent = ltrTable[location][size];
    const result = {
      currency: "CZK",
      location: loc.label,
      size: sz.label,
      season: seasonKey,
      averageNightlyRate: r.adr,
      occupancyRate: Math.round(r.occupancy * 100) / 100,
      grossMonthlyRevenue: r.gross,
      managementCommission: r.commission,
      managementCommissionRate: MGMT_FEE,
      netMonthlyIncomeForOwner: r.net,
      netYearlyAverage: yearly.net * 12,
      longTermRentBenchmark: longTermRent,
      multipleVsLongTermRent: Math.round(r.net / longTermRent * 10) / 10,
      note: "Indicative estimate based on Prague market benchmarks; amounts exclude VAT. Cleaning and laundry are paid by guests as part of each booking and handled by antam homes, so they do not reduce the owner's income. Utilities (electricity, water, gas) are paid by the owner and are not included."
    };
    return {
      content: [
        {
          type: "text",
          text: `${loc.label}, ${sz.label}: net ~${result.netMonthlyIncomeForOwner.toLocaleString("cs-CZ")} CZK/month for the owner (gross ${result.grossMonthlyRevenue.toLocaleString("cs-CZ")} CZK, ADR ${result.averageNightlyRate} CZK, occupancy ${Math.round(r.occupancy * 100)}%). Long-term rent benchmark ~${longTermRent.toLocaleString("cs-CZ")} CZK \u2014 roughly ${result.multipleVsLongTermRent}x.`
        }
      ],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-portfolio.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
var apartments = [
  { name: "Secret garden studio I", location: "Praha 4" },
  { name: "Secret garden studio II", location: "Praha 4" },
  { name: "Secret garden loft", location: "Praha 4" },
  { name: "Modern\xED apartm\xE1n se zahradou", location: "Praha 4" },
  { name: "Klement apartment s terasou", location: "Mlad\xE1 Boleslav" },
  { name: "Klement apartment", location: "Mlad\xE1 Boleslav" },
  { name: "My Mozart studio", location: "Praha 3" }
];
var list_portfolio_default = defineTool2({
  name: "list_portfolio",
  title: "List managed apartments",
  description: "List the apartments antam homes currently prepares, photographs and manages, with their locations.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: apartments.map((a, i) => `${i + 1}. ${a.name} \u2014 ${a.location}`).join("\n") + "\n\nComing soon: the portfolio is expanding to a total of 10 apartments across Prague."
      }
    ],
    structuredContent: {
      apartments,
      total: apartments.length,
      plannedTotalInPrague: 10
    }
  })
});

// src/lib/mcp/tools/get-services.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
var services = [
  { title: "Listing & profesion\xE1ln\xED prezentace", description: "Fotky, popis, pravidla a nastaven\xED bytu na platform\xE1ch tak, aby p\u0159it\xE1hl pozornost." },
  { title: "Dynamick\xE9 ceny", description: "Cenu lad\xEDme podle sez\xF3ny, obsazenosti a aktu\xE1ln\xED popt\xE1vky, aby byt vyd\u011Bl\xE1val naplno." },
  { title: "Komunikace s hosty", description: "Dotazy, informace k p\u0159\xEDjezdu, pr\u016Fb\u011B\u017En\xE1 podpora a rychl\xE9 \u0159e\u0161en\xED situac\xED." },
  { title: "\xDAklid a kontrola kvality", description: "Po ka\u017Ed\xE9m pobytu byt kontrolujeme a hl\xEDd\xE1me detaily, aby z\u016Fstal v dobr\xE9m stavu." },
  { title: "\xDAdr\u017Eba a \u0159e\u0161en\xED probl\xE9m\u016F", description: "Drobn\xE9 opravy, pohotov\xE9 z\xE1sahy a koordinace \u0159emesln\xEDk\u016F, kdy\u017E je pot\u0159eba." },
  { title: "M\u011Bs\xED\u010Dn\xED reporting", description: "Jasn\xFD p\u0159ehled rezervac\xED, v\xFDnos\u016F, n\xE1klad\u016F a d\u016Fle\u017Eit\xFDch informac\xED o bytu." }
];
var faq = [
  { question: "Mus\xED b\xFDt byt u\u017E p\u0159ipraven\xFD?", answer: "Ne. Um\xEDme se pod\xEDvat i na byt p\u0159ed spu\u0161t\u011Bn\xEDm a \u0159\xEDct, co d\xE1v\xE1 smysl p\u0159ipravit." },
  { question: "\u0158e\u0161\xEDte Airbnb i Booking.com?", answer: "Ano. Platformy vol\xEDme podle bytu, lokality a typu host\u016F." },
  { question: "M\u016F\u017Eu byt n\u011Bkdy vyu\u017E\xEDt pro sebe?", answer: "Ano. Vybran\xE9 term\xEDny lze v kalend\xE1\u0159i dop\u0159edu zablokovat." },
  { question: "Jak budu v\u011Bd\u011Bt, co byt vyd\u011Bl\xE1v\xE1?", answer: "Ka\u017Ed\xFD m\u011Bs\xEDc dostanete p\u0159ehled: kolik noc\xED bylo obsazeno, jak\xFD byl v\xFDnos, kolik \u010Dinila na\u0161e provize 25 % a co jsme v byt\u011B \u0159e\u0161ili. V\u0161e na jednu stranu, bez slo\u017Eit\xFDch tabulek." },
  { question: "Kolik spr\xE1va stoj\xED?", answer: "Provize je 25 % z v\xFDnosu z ubytov\xE1n\xED a je kone\u010Dn\xE1 \u2014 bez fixn\xEDch ani m\u011Bs\xED\u010Dn\xEDch poplatk\u016F. Pokr\xFDv\xE1 i internet, hygienick\xE9 pot\u0159eby pro hosty, \u010Distic\xED prost\u0159edky a drobn\xE9 opravy do 1 000 K\u010D m\u011Bs\xED\u010Dn\u011B. \u010C\xE1stky uv\xE1d\xEDme bez DPH." },
  { question: "Kdo plat\xED \xFAklid a energie?", answer: "\xDAklid a pran\xED pr\xE1dla hrad\xED host v cen\u011B rezervace a zaji\u0161\u0165uje je antam homes \u2014 v\xFDnos majitele nesni\u017Euj\xED. Energie (elekt\u0159ina, voda, plyn) hrad\xED majitel." },
  { question: "Jak dlouho spolupr\xE1ce trv\xE1 a jak ji ukon\u010D\xEDm?", answer: "Smlouva je na dobu neur\u010Ditou s v\xFDpov\u011Bdn\xED lh\u016Ftou 4 m\u011Bs\xEDce. Potvrzen\xE9 rezervace se b\u011Bhem v\xFDpov\u011Bdn\xED lh\u016Fty je\u0161t\u011B dokon\u010D\xED." },
  { question: "Kdy a jak dostanu vy\xFA\u010Dtov\xE1n\xED?", answer: "M\u011Bs\xED\u010Dn\u011B zp\u011Btn\u011B: p\u0159ehled rezervac\xED a v\xFDnos\u016F z platforem (Airbnb, Booking.com) spolu s fakturou na provizi." }
];
var get_services_default = defineTool3({
  name: "get_services_and_faq",
  title: "Get services and FAQ",
  description: "Get what antam homes does for apartment owners (full short-term rental management) plus the frequently asked questions and answers from the website.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: [
          "Services:",
          ...services.map((s) => `- ${s.title}: ${s.description}`),
          "",
          "FAQ:",
          ...faq.map((f) => `Q: ${f.question}
A: ${f.answer}`)
        ].join("\n")
      }
    ],
    structuredContent: { services, faq, managementCommissionRate: 0.25 }
  })
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
var get_contact_default = defineTool4({
  name: "get_contact_info",
  title: "Get contact information",
  description: "Get antam homes contact details and how an apartment owner can start a no-obligation conversation about their apartment.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      company: "Donut Point, s.r.o.",
      companyId: "21904022",
      registeredSeat: "P\u0159\xED\u010Dn\xE1 1892/4, Nov\xE9 M\u011Bsto, 110 00 Praha 1",
      brand: "antam homes",
      email: "antamhomes@gmail.com",
      phone: "727 952 459",
      officePhone: "607 338 126",
      website: "https://www.antamhomes.com",
      vietnameseVersion: "https://www.antamhomes.com/vn",
      serviceArea: "Praha a okol\xED",
      languages: ["\u010De\u0161tina", "Ti\u1EBFng Vi\u1EC7t"]
    };
    return {
      content: [
        {
          type: "text",
          text: `antam homes (Donut Point, s.r.o., I\u010CO 21904022)
Email: ${info.email}
Telefon: ${info.phone}
Kancel\xE1\u0159: ${info.officePhone}
Web: ${info.website} (Vietnamese: ${info.vietnameseVersion})
Oblast: ${info.serviceArea}`
        }
      ],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "antamhome",
  title: "Antamhome",
  version: "0.1.0",
  instructions: "Tools for antam homes, a short-term rental (Airbnb/Booking) management company for apartment owners in Prague. Use `estimate_rental_yield` to estimate an owner's monthly net income for a given Prague district and apartment size, `list_portfolio` for the apartments under management, `get_services_and_faq` for what the company does, and `get_contact_info` for contact details. All data is public marketing information.",
  tools: [estimate_yield_default, list_portfolio_default, get_services_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
