// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/estimate-yield.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod";

// src/lib/yield.ts
var MEDIAN_AREA = {
  "1kk": 35,
  "2kk": 53,
  "3kk": 71,
  "4kk": 88
};
var BASE_GUESTS = { "1kk": 4, "2kk": 6, "3kk": 8, "4kk": 10 };
var guestsFor = (size) => BASE_GUESTS[size];
var isMeasured = (loc) => loc in MARKET_STR;
var MARKET_STR = {
  praha1: { "1BR": { adr: 2917, revpar: 2207.5, nMean: 1675, nMin: 1606 }, "2BR": { adr: 4507, revpar: 3399.3, nMean: 904, nMin: 866 }, "3BR": { adr: 6576, revpar: 4924.8, nMean: 320, nMin: 308 } },
  praha2: { "1BR": { adr: 2419, revpar: 1739.9, nMean: 920, nMin: 869 }, "2BR": { adr: 3748, revpar: 2831.4, nMean: 361, nMin: 346 }, "3BR": { adr: 5874, revpar: 4278.2, nMean: 128, nMin: 120 } },
  praha3: { "1BR": { adr: 2130, revpar: 1568.9, nMean: 626, nMin: 592 }, "2BR": { adr: 3085, revpar: 2303.5, nMean: 179, nMin: 162 } },
  praha4: { "1BR": { adr: 1810, revpar: 1254, nMean: 184, nMin: 158 }, "2BR": { adr: 2539, revpar: 1697, nMean: 69, nMin: 60 } },
  praha5: { "1BR": { adr: 2259, revpar: 1579.7, nMean: 452, nMin: 408 }, "2BR": { adr: 3378, revpar: 2363.4, nMean: 183, nMin: 158 }, "3BR": { adr: 5599, revpar: 3710.5, nMean: 74, nMin: 65 } },
  praha6: { "1BR": { adr: 1873, revpar: 1286.6, nMean: 155, nMin: 144 }, "2BR": { adr: 2913, revpar: 1878.9, nMean: 83, nMin: 79 } },
  praha7: { "1BR": { adr: 2105, revpar: 1507, nMean: 215, nMin: 196 }, "2BR": { adr: 3336, revpar: 2087.1, nMean: 98, nMin: 91 } },
  praha8: { "1BR": { adr: 2532, revpar: 1902.3, nMean: 350, nMin: 336 }, "2BR": { adr: 3654, revpar: 2508, nMean: 92, nMin: 86 } },
  praha9: { "1BR": { adr: 2065, revpar: 1363.9, nMean: 76, nMin: 64 } }
};
var SIZE_RATIO = {
  "2BR/1BR": { adr: 1.525, revpar: 1.517 },
  "3BR/2BR": { adr: 1.514, revpar: 1.481 },
  /** Přímý poměr přes dvě pásma. Spočítaný z týchž řad jako oba sousední
   *  (čtvrti se solidním vzorkem obou pásem, váženo nabídkami), ne jejich
   *  součin: řetězit dva odvozené poměry zesiluje chybu. Rozhodnutí
   *  31. 8. 2026 po rekonciliaci jedenácti bytů. */
  "3BR/1BR": { adr: 2.329, revpar: 2.304 }
};
var RATIO_OF = {
  "1BR>2BR": SIZE_RATIO["2BR/1BR"],
  "2BR>3BR": SIZE_RATIO["3BR/2BR"],
  "1BR>3BR": SIZE_RATIO["3BR/1BR"]
};
var BAND_ORDER = ["1BR", "2BR", "3BR"];
var marketCell = (loc, band) => {
  const own = MARKET_STR[loc][band];
  if (own) return { ...own, derived: false };
  const target = BAND_ORDER.indexOf(band);
  const donors = BAND_ORDER.filter((b) => b !== band && MARKET_STR[loc][b]).sort((a, b) => {
    const da = Math.abs(BAND_ORDER.indexOf(a) - target), db = Math.abs(BAND_ORDER.indexOf(b) - target);
    return da !== db ? da - db : MARKET_STR[loc][b].nMean - MARKET_STR[loc][a].nMean;
  });
  for (const from of donors) {
    const up = BAND_ORDER.indexOf(from) < BAND_ORDER.indexOf(band);
    const k = RATIO_OF[up ? `${from}>${band}` : `${band}>${from}`];
    if (!k) continue;
    const src = MARKET_STR[loc][from];
    return {
      adr: Math.round(up ? src.adr * k.adr : src.adr / k.adr),
      revpar: up ? src.revpar * k.revpar : src.revpar / k.revpar,
      nMean: src.nMean,
      nMin: src.nMin,
      derived: true
    };
  }
  return null;
};
var OPERATOR_FACTOR_DEFAULT_PUBLIC = 1.1;
var OPERATOR_FACTOR_DEFAULT = 1.1;
var OPERATOR_EVIDENCE = {
  // PŘEMĚŘENO 2. 9. 2026 (audit shodných období). Dřívějších 0,99 se nedalo
  // reprodukovat — odvození nebylo nikde uložené. Nové měření: 12 uzavřených
  // měsíců 2025_08..2026_07, tržba za ubytování PO SLEVÁCH proti avg_revenue
  // okresu z data/pricelabs-2026-08/praha1.json.
  praha1: { measured: 1.032, weight: 1, sample: "3 byty \xD7 12 m\u011Bs\xEDc\u016F (402 1,126 \xB7 405 1,028 \xB7 302 0,942)" },
  praha3: { measured: 1.21, weight: 0.5, sample: "2 byty (Modern AC 1,31 / 139 dn\xED \xB7 Garden APT 1,21 / 54 dn\xED)" },
  praha5: { measured: 1.08, weight: 1, sample: "1 byt (Mozart, 113 dn\xED)" }
};
var publicFactorFrom = (measured, weight) => measured <= OPERATOR_FACTOR_DEFAULT_PUBLIC ? measured : Math.round((OPERATOR_FACTOR_DEFAULT_PUBLIC + weight * (measured - OPERATOR_FACTOR_DEFAULT_PUBLIC)) * 1e3) / 1e3;
var OPERATOR_FACTOR_PUBLIC = {
  // Praha 2 tu měla ruční 0,95. Zrušeno 2. 9. 2026: bez měření platí výchozí
  // 1,10 jako pro každý jiný neměřený okres (viz operatorFactor níž).
  ...Object.fromEntries(
    Object.entries(OPERATOR_EVIDENCE).map(([loc, e]) => [loc, publicFactorFrom(e.measured, e.weight)])
  )
};
var OPERATOR_FACTOR_INTERNAL = OPERATOR_FACTOR_PUBLIC;
var AVAILABILITY = 0.92;
var operatorFactor = (loc, scope = "public") => (scope === "public" ? OPERATOR_FACTOR_PUBLIC : OPERATOR_FACTOR_INTERNAL)[loc] ?? (scope === "public" ? OPERATOR_FACTOR_DEFAULT_PUBLIC : OPERATOR_FACTOR_DEFAULT);
var BAND_BLEND = {
  "1kk": { base: "1BR" },
  "2kk": { base: "1BR", next: "2BR", lo: 40, hi: 55 },
  "3kk": { base: "2BR", next: "3BR", lo: 65, hi: 95 },
  "4kk": { base: "3BR" }
};
var bandWeight = (size, m2) => {
  const b = BAND_BLEND[size];
  if (!b.next || b.lo === void 0 || b.hi === void 0) return 0;
  return Math.min(1, Math.max(0, (m2 - b.lo) / (b.hi - b.lo)));
};
var bandForSize = (size, m2) => {
  const b = BAND_BLEND[size];
  return b.next && bandWeight(size, m2) >= 0.5 ? b.next : b.base;
};
var B = (id, minM2, maxM2, representativeM2) => ({ id, labelKey: `calc_size_${id}`, minM2, maxM2, representativeM2, supported: representativeM2 !== null });
var SIZE_BUCKETS_BY_VERSION = {
  "2026-08-31.1": {
    // p25 30 · p50 34 · p75 40 · p95 49 — bez překlopení, dělí rozložení
    "1kk": [B("s", null, 30, 28), B("m", 31, 40, 35), B("l", 41, 49, 45), B("xl", 50, null, null)],
    // překlopení 1BR→2BR na 40 a 55 · p95 80
    "2kk": [B("s", null, 40, 38), B("m", 41, 55, 50), B("l", 56, 80, 63), B("xl", 81, null, null)],
    // překlopení 2BR→3BR na 65 a 95 · p95 120
    "3kk": [B("s", null, 65, 63), B("m", 66, 95, 78), B("l", 96, 120, 106), B("xl", 121, null, null)],
    // p25 93 · p50 115 · p75 132 · p95 151 — bez překlopení (chybí pásmo 4BR)
    "4kk": [B("s", null, 93, 85), B("m", 94, 132, 116), B("l", 133, 151, 142), B("xl", 152, null, null)]
  }
};
var LOW_BLEND = 0.5;
var SPREAD = { low: 0.92, high: 1.08, minWidth: 0.08, derivedWiden: 1.6 };
var MARKET_CTVRT = {
  /**
   * Staré Město: přetaženo 5. 9. 2026 S MĚSÍČNÍ ŘADOU, geometrie „Old Town
   * official boundary (openstreetmap)" schválená člověkem (anglický label,
   * jako „New Town" u Nového Města). Surové odpovědi
   * data/pricelabs-raw/stare_mesto.{1BR,2BR,3BR}.raw.json, artefakt
   * data/pricelabs-2026-09/stare_mesto.json. Tím zmizelo z RECONSTRUCTED_CELLS.
   *
   * Co re-pull ukázal proti rekonstrukci z 30. 8.: 1BR RevPAR +0,07 % a ADR
   * +0,14 % (tentýž polygon), 2BR RevPAR +1,1 %, 3BR +3,7 % (u ADR i RevPAR
   * stejně — jiná cenová úroveň rekonstrukce, ne jiný polygon). Původní
   * „nMean" 533 / 297 / 110 byla ve skutečnosti MINIMA řady (dnešní nMin
   * 533 / 296 / 111); skutečný nMean je 567 / 321 / 114. Ve sporu kód vs DB
   * (2BR 3733,7 vs 3479; 3BR 4809,4 vs 4560) měl pravdu kód; DB řádky byly
   * záměrně přepsané ventilem antam.allow_history_rewrite v téže transakci.
   */
  stare_mesto: {
    label: "Star\xE9 M\u011Bsto",
    parents: ["praha1"],
    bands: {
      "1BR": { adr: 3211, revpar: 2469.2, nMean: 567, nMin: 533, basis: "measured" },
      "2BR": { adr: 4867, revpar: 3774.2, nMean: 321, nMin: 296, basis: "measured" },
      "3BR": { adr: 6588, revpar: 4987.8, nMean: 114, nMin: 111, basis: "measured" }
    }
  },
  /**
   * Nové Město leží v Praze 1 I v Praze 2 — katastr je rozdělený, takže
   * `parents` má obě. Není to kompromis kvůli UX: kdyby tu byla jen praha1,
   * majitel bytu v novoměstské části Prahy 2 by dostal okresní číslo, aniž
   * by se ho kdokoli zeptal.
   *
   * Všechna tři pásma PŘÍMO MĚŘENÁ, jeden pull 2. 9. 2026, geometrie
   * „New Town official boundary (openstreetmap)", okno 2025_08..2026_07.
   * Surová odpověď PriceLabs je v repu a artefakt se z ní reprodukuje:
   * data/pricelabs-raw/nove_mesto.{1BR,2BR,3BR}.raw.json,
   * artefakt data/pricelabs-2026-09/nove_mesto.json.
   * Vzorky jsou velké (nMin 1226 / 608 / 219), takže váha je u všech 1,0.
   */
  nove_mesto: {
    label: "Nov\xE9 M\u011Bsto",
    parents: ["praha1", "praha2"],
    bands: {
      "1BR": { adr: 2627, revpar: 1959.9, nMean: 1288, nMin: 1226, basis: "measured" },
      "2BR": { adr: 4031, revpar: 3045.7, nMean: 619, nMin: 608, basis: "measured" },
      "3BR": { adr: 6503, revpar: 4851.3, nMean: 231, nMin: 219, basis: "measured" }
    }
  },
  /**
   * Vinohrady leží v Praze 2 i v Praze 3, takže jeden pull (2. 9. 2026)
   * obsluhuje oba kontexty: praha2/vinohrady (LTR +0,6 %, n=63) i
   * praha3/vinohrady (+3,5 %, n=32). Geometrie
   * „Vinohrady official boundary (openstreetmap)", okno 2025_08..2026_07,
   * surové odpovědi v data/pricelabs-raw/vinohrady.{1BR,2BR,3BR}.raw.json.
   *
   * POZOR na 3BR: nMean 71 spadá do pásma 50–99, takže `ctvrtWeight` dá
   * váhu 0,75 — je to PRVNÍ čtvrťové pásmo, které nejede na plnou váhu.
   * Výsledek je 75 % Vinohrad + 25 % okresu, a protože geometrie patří
   * dvěma obvodům, vyjde pro Prahu 2 a Prahu 3 jiné číslo. Tak to pravidlo
   * má fungovat; není to výjimka ani chyba.
   */
  vinohrady: {
    label: "Vinohrady",
    parents: ["praha2", "praha3"],
    bands: {
      "1BR": { adr: 2335, revpar: 1669.8, nMean: 616, nMin: 586, basis: "measured" },
      "2BR": { adr: 3656, revpar: 2710.4, nMean: 227, nMin: 215, basis: "measured" },
      "3BR": { adr: 5437, revpar: 3946.1, nMean: 71, nMin: 63, basis: "measured" }
    }
  },
  /**
   * Žižkov leží celý v Praze 3 (jediný kontext praha3/zizkov, LTR −3,8 %,
   * n=79). Pull 4. 9. 2026, geometrie „Žižkov official boundary
   * (openstreetmap)" schválená člověkem znak po znaku, okno 2025_08..2026_07,
   * surové odpovědi data/pricelabs-raw/zizkov.{1BR,2BR,3BR}.raw.json,
   * artefakt data/pricelabs-2026-09/zizkov.json.
   *
   * Na STR je Praha 3 z ~86 % Žižkov (1BR 537 z 626, 2BR 152 z 179, 3BR
   * 44 z 46 nabídek okresu), takže 1BR a 2BR sedí na okres na procento
   * (RevPAR 0,985 / 0,990 okresu). Předregistrace čekala podíl 35–45 %;
   * mýlil se předpoklad, ne polygon — podíl je 0,85–0,86 ve všech dvanácti
   * měsících, tak se chová podmnožina.
   *
   * POZOR na 3BR: nMean 44 dává `ctvrtWeight` 0,5 a okresní buňka P3 3BR
   * NENÍ měřená — MARKET_STR.praha3 pásmo 3BR nemá a `marketCell` ho odvozuje
   * z 2BR poměrem (RevPAR 2303,5 × 1,481 = 3411,5). Veřejný výsledek je tedy
   * 50 % naměřeného Žižkova (4333,9) + 50 % odvozeného okresu = 3872,7,
   * s příznakem `derived` a rozšířeným rozpětím. Naměřených 4334 se
   * nepublikuje přímo; přesně na to je shrinkage. Že odvozených 3411 leží
   * hluboko pod naměřeným Žižkovem i pod potlačeným tenkým měřením okresu
   * (4211, n≈46), je otázka kalibrace okresního pásma a řeší se ZVLÁŠŤ,
   * ne v téhle integraci (docs/calculator-model.md, otevřené body).
   */
  zizkov: {
    label: "\u017Di\u017Ekov",
    parents: ["praha3"],
    bands: {
      "1BR": { adr: 2085, revpar: 1545, nMean: 537, nMin: 510, basis: "measured" },
      "2BR": { adr: 3052, revpar: 2279.6, nMean: 152, nMin: 135, basis: "measured" },
      "3BR": { adr: 6006, revpar: 4333.9, nMean: 44, nMin: 38, basis: "measured" }
    }
  },
  /**
   * Smíchov leží celý v Praze 5 (jediný kontext praha5/smichov, LTR +7,7 %,
   * n=101 — nejlepší nájemní vzorek ze všech čtvrtí). Pull 4. 9. 2026,
   * geometrie „Smíchov official boundary (openstreetmap)" schválená člověkem
   * znak po znaku, okno 2025_08..2026_07, surové odpovědi
   * data/pricelabs-raw/smichov.{1BR,2BR,3BR}.raw.json, artefakt
   * data/pricelabs-2026-09/smichov.json. 1BR a 2BR přišly jako 13 měsíců
   * (neuzavřený 2026_08 navíc); obálka ho drží, extrakce ho vyřadila
   * kalendářním pravidlem.
   *
   * Na STR je Smíchov 72–79 % Prahy 5 a sedí na okres ve všech pásmech
   * (RevPAR 0,99 / 1,01 / 0,96 okresu). Nájemní prémie +7,7 % se na STR
   * NEPŘENÁŠÍ — stejný vzorec jako Žižkov (LTR −3,8 %, STR −1,5 %). Čtvrť
   * tedy pro majitele v Praze 5 skoro nic nemění; je tu proto, že to teď
   * je změřené, ne odhadnuté.
   *
   * 3BR: nMean 58 → `ctvrtWeight` 0,75, nMin 50 přesně na prahu
   * spolehlivosti. Na rozdíl od Žižkova je okresní rodič P5 3BR MĚŘENÝ
   * (nMin 65), takže blend je 75 % naměřené čtvrti + 25 % naměřeného
   * okresu, bez příznaku derived.
   */
  smichov: {
    label: "Sm\xEDchov",
    parents: ["praha5"],
    bands: {
      "1BR": { adr: 2263, revpar: 1566.6, nMean: 327, nMin: 293, basis: "measured" },
      "2BR": { adr: 3348, revpar: 2385.4, nMean: 145, nMin: 125, basis: "measured" },
      "3BR": { adr: 5524, revpar: 3562.1, nMean: 58, nMin: 50, basis: "measured" }
    }
  },
  /**
   * Karlín leží celý v Praze 8 (jediný kontext praha8/karlin, LTR +11,4 %,
   * n=36 — největší nájemní prémie v registru). Pull 4. 9. 2026, geometrie
   * „Karlín official boundary (openstreetmap)" schválená člověkem znak po
   * znaku, okno 2025_08..2026_07, surové odpovědi
   * data/pricelabs-raw/karlin.{1BR,2BR,3BR}.raw.json, artefakt
   * data/pricelabs-2026-09/karlin.json.
   *
   * Tohle je první čtvrť, kde se lokální efekt na STR opravdu ukázal:
   * Karlín je nad Prahou 8 ve všech pásmech (RevPAR 1,086 / 1,082 / 1,069
   * okresu), u 1BR v každém z 12 měsíců, při stabilním podílu 70–90 %
   * okresní nabídky. Žižkov a Smíchov seděly na okres bez ohledu na nájemní
   * rozestup; Karlín je místo, kde se nájem i STR rozcházejí stejným směrem.
   * „Karlín effect" z docs/calculator-model.md je tím změřený, ne
   * předpokládaný.
   *
   * VÁHY: 2BR nMean 64 → 0,75 (první čtvrťové 2BR pod plnou vahou).
   * 3BR nMean 43 → 0,5 a okresní rodič P8 3BR NENÍ měřený (potlačené
   * n≈47, `marketCell` odvozuje z 2BR: 2508,0 × 1,481 = 3714,3) — týž
   * režim jako Žižkov: 50 % naměřených 3981,1 + 50 % odvozených 3714,3
   * = 3847,7 s příznakem `derived`. Rozdíl proti Žižkovu: tady jsou
   * naměřená čtvrť a odvozený okres blízko (+7 %), takže shrinkage skoro
   * nic nemění.
   */
  karlin: {
    label: "Karl\xEDn",
    parents: ["praha8"],
    bands: {
      "1BR": { adr: 2671, revpar: 2066.8, nMean: 269, nMin: 253, basis: "measured" },
      "2BR": { adr: 3928, revpar: 2713.1, nMean: 64, nMin: 56, basis: "measured" },
      "3BR": { adr: 5709, revpar: 3981.1, nMean: 43, nMin: 36, basis: "measured" }
    }
  }
};
var ctvrtWeight = (n) => n >= 100 ? 1 : n >= 50 ? 0.75 : n >= 25 ? 0.5 : 0;
var localCell = (loc, band, ctvrt) => {
  const district = marketCell(loc, band);
  const c = ctvrt ? MARKET_CTVRT[ctvrt] : void 0;
  if (!c || !c.parents.includes(loc)) return district;
  const own = c.bands[band];
  if (!own || own.basis !== "measured" || !district) return district;
  const w = ctvrtWeight(own.nMean);
  if (w === 0) return district;
  return {
    adr: Math.round(own.adr * w + district.adr * (1 - w)),
    revpar: own.revpar * w + district.revpar * (1 - w),
    nMean: own.nMean,
    nMin: own.nMin,
    derived: district.derived && w < 1
  };
};
var marketOccPct = (loc, band) => {
  const cell = marketCell(loc, band);
  return cell ? Math.round(cell.revpar / cell.adr * 100) : null;
};
var MARKET_OCC = {
  praha1: marketOccPct("praha1", "2BR"),
  praha3: marketOccPct("praha3", "2BR"),
  praha4: marketOccPct("praha4", "1BR"),
  praha5: marketOccPct("praha5", "1BR"),
  mb: 72
};
var SEASONS_BY_LOC = {
  praha1: { summer: { adr: 1.053, revpar: 1.092 }, winter: { adr: 0.798, revpar: 0.69 }, xmas: { adr: 1.437, revpar: 1.599 } },
  praha2: { summer: { adr: 1.045, revpar: 1.09 }, winter: { adr: 0.809, revpar: 0.691 }, xmas: { adr: 1.448, revpar: 1.603 } },
  praha3: { summer: { adr: 1.04, revpar: 1.086 }, winter: { adr: 0.824, revpar: 0.713 }, xmas: { adr: 1.427, revpar: 1.544 } },
  praha4: { summer: { adr: 1.034, revpar: 1.093 }, winter: { adr: 0.856, revpar: 0.714 }, xmas: { adr: 1.338, revpar: 1.491 } },
  praha5: { summer: { adr: 1.047, revpar: 1.11 }, winter: { adr: 0.82, revpar: 0.678 }, xmas: { adr: 1.389, revpar: 1.521 } },
  praha6: { summer: { adr: 1.031, revpar: 1.11 }, winter: { adr: 0.892, revpar: 0.727 }, xmas: { adr: 1.215, revpar: 1.322 } },
  praha7: { summer: { adr: 1.021, revpar: 1.089 }, winter: { adr: 0.861, revpar: 0.707 }, xmas: { adr: 1.408, revpar: 1.548 } },
  praha8: { summer: { adr: 1.036, revpar: 1.084 }, winter: { adr: 0.815, revpar: 0.697 }, xmas: { adr: 1.49, revpar: 1.624 } },
  praha9: { summer: { adr: 1.013, revpar: 1.067 }, winter: { adr: 0.922, revpar: 0.784 }, xmas: { adr: 1.219, revpar: 1.393 } }
};
var RENT_SLOPE = -0.2565;
var RENT_INTERCEPT = {
  praha1: 7.301,
  praha2: 7.285,
  praha3: 7.238,
  praha4: 7.121,
  praha5: 7.152,
  praha6: 7.161,
  praha7: 7.273,
  praha8: 7.159,
  praha9: 7.154,
  praha10: 7.115
};
var TYPICAL_AREA = { "praha1": { "1kk": 34, "2kk": 65, "3kk": 91, "4kk": 124 }, "praha2": { "1kk": 41, "2kk": 52, "3kk": 94, "4kk": 123 }, "praha3": { "1kk": 40, "2kk": 55, "3kk": 87, "4kk": 115 }, "praha4": { "1kk": 32, "2kk": 50, "3kk": 79, "4kk": 84 }, "praha5": { "1kk": 35, "2kk": 53, "3kk": 80, "4kk": 118 }, "praha6": { "1kk": 35, "2kk": 53, "3kk": 91, "4kk": 113 }, "praha7": { "1kk": 35, "2kk": 59, "3kk": 80, "4kk": 115 }, "praha8": { "1kk": 34, "2kk": 53, "3kk": 80, "4kk": 115 }, "praha9": { "1kk": 35, "2kk": 53, "3kk": 72, "4kk": 115 }, "praha10": { "1kk": 33, "2kk": 54, "3kk": 83, "4kk": 115 } };
var typicalArea = (loc, size) => TYPICAL_AREA[loc]?.[size] ?? MEDIAN_AREA[size];
var FURN_RENT = {
  furnished: 1.114,
  partly: 0.99,
  none: 0.938,
  mix: 1
};
var GEO = [
  { id: "praha1/nove_mesto", district: "praha1", sourceGeometry: "nove_mesto", label: "Nov\xE9 M\u011Bsto", ltr: { effect: -77e-4, n: 41 } },
  { id: "praha1/stare_mesto", district: "praha1", sourceGeometry: "stare_mesto", label: "Star\xE9 M\u011Bsto", ltr: { fallback: "district", reason: "n=11 pod prahem shrinkage" } },
  { id: "praha2/nove_mesto", district: "praha2", sourceGeometry: "nove_mesto", label: "Nov\xE9 M\u011Bsto", ltr: { effect: -0.0222, n: 26 } },
  { id: "praha2/vinohrady", district: "praha2", sourceGeometry: "vinohrady", label: "Vinohrady", ltr: { effect: 6e-3, n: 63 } },
  { id: "praha3/vinohrady", district: "praha3", sourceGeometry: "vinohrady", label: "Vinohrady", ltr: { effect: 0.0347, n: 32 } },
  { id: "praha3/zizkov", district: "praha3", sourceGeometry: "zizkov", label: "\u017Di\u017Ekov", ltr: { effect: -0.0381, n: 79 } },
  { id: "praha4/branik", district: "praha4", sourceGeometry: "branik", label: "Bran\xEDk", ltr: { effect: -0.01, n: 16 } },
  { id: "praha4/chodov", district: "praha4", sourceGeometry: "chodov", label: "Chodov", ltr: { effect: -4e-4, n: 24 } },
  { id: "praha4/krc", district: "praha4", sourceGeometry: "krc", label: "Kr\u010D", ltr: { effect: -91e-4, n: 21 } },
  { id: "praha4/michle", district: "praha4", sourceGeometry: "michle", label: "Michle", ltr: { effect: 47e-4, n: 22 } },
  { id: "praha4/modrany", district: "praha4", sourceGeometry: "modrany", label: "Mod\u0159any", ltr: { effect: 46e-4, n: 22 } },
  { id: "praha4/nusle", district: "praha4", sourceGeometry: "nusle", label: "Nusle", ltr: { effect: 0.0407, n: 48 } },
  { id: "praha5/hlubocepy", district: "praha5", sourceGeometry: "hlubocepy", label: "Hlubo\u010Depy", ltr: { effect: -0.0129, n: 37 } },
  { id: "praha5/kosire", district: "praha5", sourceGeometry: "kosire", label: "Ko\u0161\xED\u0159e", ltr: { effect: 0.0338, n: 30 } },
  { id: "praha5/smichov", district: "praha5", sourceGeometry: "smichov", label: "Sm\xEDchov", ltr: { effect: 0.0773, n: 101 } },
  { id: "praha5/stodulky", district: "praha5", sourceGeometry: "stodulky", label: "Stod\u016Flky", ltr: { effect: -0.0455, n: 48 } },
  { id: "praha6/brevnov", district: "praha6", sourceGeometry: "brevnov", label: "B\u0159evnov", ltr: { effect: 33e-4, n: 15 } },
  { id: "praha6/bubenec", district: "praha6", sourceGeometry: "bubenec", label: "Bubene\u010D", ltr: { effect: 0.0144, n: 16 } },
  { id: "praha6/dejvice", district: "praha6", sourceGeometry: "dejvice", label: "Dejvice", ltr: { effect: 0.0234, n: 15 } },
  { id: "praha6/ruzyne", district: "praha6", sourceGeometry: "ruzyne", label: "Ruzyn\u011B", ltr: { effect: -63e-4, n: 12 } },
  { id: "praha7/holesovice", district: "praha7", sourceGeometry: "holesovice", label: "Hole\u0161ovice", ltr: { effect: 8e-4, n: 62 } },
  { id: "praha8/karlin", district: "praha8", sourceGeometry: "karlin", label: "Karl\xEDn", ltr: { effect: 0.1143, n: 36 } },
  { id: "praha8/kobylisy", district: "praha8", sourceGeometry: "kobylisy", label: "Kobylisy", ltr: { effect: -0.03, n: 19 } },
  { id: "praha8/liben", district: "praha8", sourceGeometry: "liben", label: "Libe\u0148", ltr: { effect: -0.0235, n: 29 } },
  { id: "praha8/troja", district: "praha8", sourceGeometry: "troja", label: "Troja", ltr: { effect: -81e-4, n: 14 } },
  { id: "praha9/cerny_most", district: "praha9", sourceGeometry: "cerny_most", label: "\u010Cern\xFD Most", ltr: { effect: -0.012, n: 12 } },
  { id: "praha9/hloubetin", district: "praha9", sourceGeometry: "hloubetin", label: "Hloub\u011Bt\xEDn", ltr: { effect: 22e-4, n: 19 } },
  { id: "praha9/liben", district: "praha9", sourceGeometry: "liben", label: "Libe\u0148", ltr: { effect: -63e-4, n: 13 } },
  { id: "praha9/prosek", district: "praha9", sourceGeometry: "prosek", label: "Prosek", ltr: { effect: -0.012, n: 14 } },
  { id: "praha9/vysocany", district: "praha9", sourceGeometry: "vysocany", label: "Vyso\u010Dany", ltr: { effect: 82e-4, n: 37 } },
  { id: "praha10/hostivar", district: "praha10", sourceGeometry: "hostivar", label: "Hostiva\u0159", ltr: { effect: 5e-4, n: 18 } },
  { id: "praha10/strasnice", district: "praha10", sourceGeometry: "strasnice", label: "Stra\u0161nice", ltr: { effect: -37e-4, n: 37 } },
  { id: "praha10/vrsovice", district: "praha10", sourceGeometry: "vrsovice", label: "Vr\u0161ovice", ltr: { effect: 0.0282, n: 40 } },
  { id: "praha10/zabehlice", district: "praha10", sourceGeometry: "zabehlice", label: "Z\xE1b\u011Bhlice", ltr: { effect: -0.0182, n: 18 } }
];
var geoContext = (district, sourceGeometry) => sourceGeometry ? GEO.find((g) => g.district === district && g.sourceGeometry === sourceGeometry) : void 0;
var ctvrtRentFactor = (loc, ctvrt) => {
  const g = geoContext(loc, ctvrt);
  return g && "effect" in g.ltr ? Math.exp(g.ltr.effect) : 1;
};
var rentFor = (loc, size, m2 = MEDIAN_AREA[size], furn = "mix", ctvrt) => Math.round(m2 * Math.exp(RENT_INTERCEPT[loc]) * Math.pow(m2, RENT_SLOPE) * FURN_RENT[furn] * ctvrtRentFactor(loc, ctvrt));
var locKeyOf = (loc) => {
  const m = /^Praha (\d+)$/.exec(loc);
  return m ? `praha${m[1]}` : null;
};
var ratioFor = (loc, m2, ownerMonthlyCzk) => {
  const key = locKeyOf(loc);
  if (!key) return null;
  return Math.round(ownerMonthlyCzk / rentFor(key, "2kk", m2) * 10) / 10;
};
var ROOMS = { "1kk": 1, "2kk": 2, "3kk": 3, "4kk": 4 };
var DAMAGE_COVER_PER_ROOM = 5e3;
var DAMAGE_COVER_MAX = 25e3;
var annualDamageCover = (rooms) => Math.min(Math.max(0, Math.round(rooms)) * DAMAGE_COVER_PER_ROOM, DAMAGE_COVER_MAX);
var OCCUPANCY_BY_FLAT = [
  { name: "Elegant Museum View\xA0Apartment", loc: "Praha 1", kat: "Nov\xE9 M\u011Bsto", m2: 52, bedrooms: 2, occupancy: 96, market: MARKET_OCC.praha1, days: 319 },
  { name: "Modern Museum View\xA0Apartment", loc: "Praha 1", kat: "Nov\xE9 M\u011Bsto", m2: 52, bedrooms: 2, occupancy: 94, market: MARKET_OCC.praha1, days: 318 },
  { name: "Modern AC\xA0Apartment", loc: "Praha 3", kat: "\u017Di\u017Ekov", m2: 55, bedrooms: 2, occupancy: 96, market: MARKET_OCC.praha3, days: 139 },
  { name: "Modern\xED apartm\xE1n se\xA0zahradou", loc: "Praha 3", kat: "\u017Di\u017Ekov", m2: 60, bedrooms: 2, occupancy: 85, market: MARKET_OCC.praha3, days: 54 },
  { name: "Klement apartment s\xA0terasou", loc: "Mlad\xE1 Boleslav", kat: "Mlad\xE1 Boleslav", m2: 85, bedrooms: 2, occupancy: 91, market: MARKET_OCC.mb, days: 54 },
  { name: "My Mozart studio", loc: "Praha 5", kat: "Sm\xEDchov", m2: 40, bedrooms: 1, occupancy: 97, market: MARKET_OCC.praha5, days: 113 }
];
var SIZE_PRESET = {
  "1kk": { m2: MEDIAN_AREA["1kk"] },
  "2kk": { m2: MEDIAN_AREA["2kk"] },
  "3kk": { m2: MEDIAN_AREA["3kk"] },
  "4kk": { m2: MEDIAN_AREA["4kk"] }
};
var MGMT_FEE = 0.3;
var PLATFORM_FEE = 0.17;
var DAYS = 30.44;
var split = (gross, occupancy) => {
  const platformFee = Math.round(PLATFORM_FEE * gross);
  const netRevenue = gross - platformFee;
  const mgmt = Math.round(netRevenue * MGMT_FEE);
  return { occupancy, gross, platformFee, netRevenue, mgmt, net: netRevenue - mgmt };
};
function ownerMonthly(location, size, { season = "year", m2, ctvrt = null, scope = "public", config } = {}) {
  const guests = guestsFor(size);
  const area = m2 ?? typicalArea(location, size);
  const band = bandForSize(size, area);
  if (!isMeasured(location)) return { supported: false, band, guests };
  const observed = scope === "internal" ? config ?? null : null;
  const cfg = observed ? { base: observed.band, next: void 0, lo: void 0, hi: void 0 } : BAND_BLEND[size];
  const usedCtvrt = ctvrt && MARKET_CTVRT[ctvrt]?.parents.includes(location) ? ctvrt : null;
  const baseCell = localCell(location, cfg.base, usedCtvrt);
  if (!baseCell) return { supported: false, band, guests };
  const nextCell = cfg.next ? localCell(location, cfg.next, usedCtvrt) : null;
  const w = nextCell && !observed ? bandWeight(size, area) : 0;
  const f = season === "year" ? { adr: 1, revpar: 1 } : SEASONS_BY_LOC[location][season];
  const shownCell = w >= 0.5 && nextCell ? nextCell : baseCell;
  const adr = Math.round(shownCell.adr * f.adr);
  const marketRevpar = shownCell.revpar * f.revpar;
  const marketOcc = Math.round(marketRevpar / adr * 1e3) / 1e3;
  const gBase = baseCell.revpar * f.revpar * DAYS;
  const gNext = nextCell ? nextCell.revpar * f.revpar * DAYS : gBase;
  let lowGross = nextCell ? gBase + LOW_BLEND * w * (gNext - gBase) : gBase * SPREAD.low;
  let highGross = nextCell ? gBase + w * (gNext - gBase) : gBase * SPREAD.high;
  const derived = baseCell.derived || !!nextCell && nextCell.derived;
  if (derived) {
    const mid = (lowGross + highGross) / 2;
    lowGross = mid - (mid - lowGross) * SPREAD.derivedWiden;
    highGross = mid + (highGross - mid) * SPREAD.derivedWiden;
  }
  if (highGross - lowGross < SPREAD.minWidth * lowGross) {
    const mid = (lowGross + highGross) / 2;
    lowGross = mid * (1 - SPREAD.minWidth / 2);
    highGross = mid * (1 + SPREAD.minWidth / 2);
  }
  const k = operatorFactor(location, scope);
  const market = split(Math.round(lowGross * k * AVAILABILITY), marketOcc);
  const antam = split(Math.round(highGross * k * AVAILABILITY), marketOcc);
  return {
    supported: true,
    band,
    adr,
    derived,
    guests,
    market,
    antam,
    low: market.net,
    high: antam.net,
    mid: Math.round((market.net + antam.net) / 2),
    trace: {
      base: cfg.base,
      next: nextCell ? cfg.next ?? null : null,
      w,
      ctvrt: usedCtvrt,
      factor: k,
      availability: AVAILABILITY,
      config: observed ? { band: observed.band, evidence: observed.evidence } : null
    }
  };
}

// src/lib/mcp/tools/estimate-yield.ts
var locations = {
  praha1: "Praha 1",
  praha2: "Praha 2",
  praha3: "Praha 3",
  praha4: "Praha 4",
  praha5: "Praha 5",
  praha6: "Praha 6",
  praha7: "Praha 7",
  praha8: "Praha 8",
  praha9: "Praha 9",
  praha10: "Praha 10"
};
var czk = (n) => n.toLocaleString("cs-CZ");
var estimate_yield_default = defineTool({
  name: "estimate_rental_yield",
  title: "Estimate short-term rental yield",
  description: "Estimate the monthly net income an apartment owner in Prague could earn with Antam Homes short-term rental management, and compare it to long-term rent. Same model and same code as the calculator on the website: realized market prices of the whole district per bedroom band (PriceLabs STR index, 12 closed months). The public model maps LAYOUT + FLOOR AREA to a market band, blending between two bands over an area range; the result is a range whose low end is the district market average and whose high end is that same market times the measured Antam operator factor. Guest capacity is not an input, never multiplies revenue, and is deliberately NOT reported: how many beds fit depends on room proportions rather than total floor area, so do not state or estimate a guest count for the owner. Districts or bands with too small a market sample (and Praha 10 for now) get an individual assessment within 24 hours instead of a number.",
  inputSchema: {
    location: z.enum(["praha1", "praha2", "praha3", "praha4", "praha5", "praha6", "praha7", "praha8", "praha9", "praha10"]).describe("Prague district of the apartment."),
    size: z.enum(["1kk", "2kk", "3kk", "4kk"]).describe("Apartment layout in Czech notation (1kk = one room with kitchenette, 3kk = two separate bedrooms plus a living room). This is the PHYSICAL layout, not a bedroom count on Airbnb and not a guest capacity: those are three different things. Layout plus floor area picks the commercial market band. 1kk = 1BR. 2kk blends 1BR to 2BR between 40 and 55 m2 (measured on Antam's own flats: 40 m2 sleeping four earns as 1BR, 52 m2 sleeping eight earns as 2BR). 3kk blends 2BR to 3BR between 65 and 95 m2 (HEURISTIC consistency correction of 31 Aug 2026, not measured: no 3kk flat has trading history yet). 4kk is capped at 3BR because no 4BR market band exists yet, so large 4kk flats are understated. Long-term rent uses the district-typical floor area of the layout (Sreality medians) unless floorAreaM2 is given."),
    floorAreaM2: z.number().int().min(18).max(140).optional().describe("Floor area in m2. Drives BOTH the commercial band blend (see `size`) and the long-term rent comparison, so it materially changes the estimate: a 3kk at 95 m2 is priced as a full 3BR product, the same layout at 65 m2 as a 2BR one. Give it whenever it is known. If omitted, the district-typical area for that layout is assumed (Sreality medians) and the answer is correspondingly less precise; the response then reports floorAreaAssumed: true."),
    season: z.enum(["year", "summer", "winter", "xmas"]).optional().describe("Season to price for. Defaults to 'year' (yearly average). Seasonal factors come from realized monthly market data of the district; summer (Apr-Oct), winter (Nov-Mar excl. December) and December compose the year exactly.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ location, size, floorAreaM2, season }) => {
    const label = locations[location];
    const sz = size;
    const m2 = floorAreaM2 ?? typicalArea(location, sz);
    const seasonKey = season ?? "year";
    const r = ownerMonthly(location, sz, { season: seasonKey, m2 });
    const longTermRent = rentFor(location, sz, m2);
    if (!r.supported) {
      const reason = isMeasured(location) ? `too few comparable listings in the ${r.band} band in ${label}` : `no district market data for ${label} yet`;
      return {
        content: [
          {
            type: "text",
            text: `${label}, ${sz} (${m2} m2): no published estimate (${reason}). Antam Homes only shows numbers where the market sample is solid. Send the address and layout and you get an individual calculation for the specific apartment within 24 hours, free and non-binding. For context, the long-term rent benchmark for ${m2} m2 is ~${czk(longTermRent)} CZK/month (median of current Sreality listings, 8/2026).`
          }
        ],
        structuredContent: {
          currency: "CZK",
          location: label,
          size: sz,
          floorAreaM2: m2,
          supported: false,
          reason,
          longTermRentBenchmark: longTermRent,
          floorAreaAssumed: floorAreaM2 === void 0,
          note: "Estimates are published only where the district market sample is solid (PriceLabs STR index). An individual assessment for any apartment is free and takes up to 24 hours."
        }
      };
    }
    const yearly = ownerMonthly(location, sz, { m2 });
    const yearlyNet = yearly.supported ? yearly.antam.net : r.antam.net;
    const yearlyMarketNet = yearly.supported ? yearly.market.net : r.market.net;
    const result = {
      currency: "CZK",
      location: label,
      size: sz,
      floorAreaM2: m2,
      /** true = caller gave no area, district-typical median assumed; estimate is less precise. */
      floorAreaAssumed: floorAreaM2 === void 0,
      supported: true,
      marketBand: r.band,
      bandDerivedFromSmallerFlats: r.derived,
      season: seasonKey,
      realizedMarketNightlyRate: r.adr,
      ownerRangeMonthly: { low: r.low, high: r.high, mid: r.mid },
      marketAverage: {
        occupancyRate: r.market.occupancy,
        grossMonthlyRevenue: r.market.gross,
        platformCommission: r.market.platformFee,
        netRevenueAfterPlatform: r.market.netRevenue,
        managementCommission: r.market.mgmt,
        netMonthlyIncomeForOwner: r.market.net,
        netYearlyAverage: yearlyMarketNet * 12,
        multipleVsLongTermRent: Math.round(r.market.net / longTermRent * 10) / 10
      },
      withAntamHomes: {
        occupancyRate: r.antam.occupancy,
        occupancyAssumption: `district market RevPAR x ${AVAILABILITY} (PriceLabs RevPAR counts available nights only) x measured Antam factor ${operatorFactor(location, "public")}; factor comes from reconciling eleven managed flats against PriceLabs, 8/2025-7/2026`,
        grossMonthlyRevenue: r.antam.gross,
        platformCommission: r.antam.platformFee,
        netRevenueAfterPlatform: r.antam.netRevenue,
        managementCommission: r.antam.mgmt,
        netMonthlyIncomeForOwner: r.antam.net,
        netYearlyAverage: yearlyNet * 12,
        multipleVsLongTermRent: Math.round(r.antam.net / longTermRent * 10) / 10
      },
      platformCommissionRate: PLATFORM_FEE,
      managementCommissionRate: MGMT_FEE,
      longTermRentBenchmark: longTermRent,
      note: "Nightly rate = realized market price of the whole district for this bedroom band (PriceLabs STR index, official district boundary, 12 closed months to 7/2026). marketAverage uses the district's market occupancy; withAntamHomes applies the measured Antam operator factor (revenue ratio against the market mean, from reconciling eleven managed flats against PriceLabs) to the same market data. It is a measured revenue ratio, not an occupancy uplift: Antam's flats run 92-96 % occupancy at 63-77 % of market ADR, so the effect shows up in revenue, not in an assumed occupancy number. The Antam Homes fee is 30 % of net revenue: what the platform pays out, after deducting the cleaning fee. The fee is final; nothing is added on top, and it also covers the Czech VAT due on the platform commission. Every apartment Antam Homes accepts for management comes with a written yearly income guarantee (at least the long-term rent plus utilities); eligibility is checked free of charge before signing, and this estimate is not that guarantee. Guests pay the cleaning fee separately; it is retained by Antam Homes. Utilities (electricity, water) are paid by the owner and are not included. Long-term rent = median of 1 300+ fresh Sreality listings (8/2026) by district and actual floor area, cross-checked against Deloitte Rent Index Q2/2026. If floorAreaM2 was not supplied, floorAreaAssumed is true and the district-typical area was used for both the band blend and the rent, which makes the estimate noticeably less precise for atypically small or large flats."
    };
    return {
      content: [
        {
          type: "text",
          text: `${label}, ${sz}, ${m2} m2 (band ${r.band}${r.derived ? ", derived from smaller flats" : ""}): owner range ~${czk(r.low)} to ${czk(r.high)} CZK/month. Realized market rate ${czk(r.adr)} CZK/night. Market average (occupancy ${Math.round(r.market.occupancy * 100)} %): owner nets ~${czk(r.market.net)} CZK/month. With Antam Homes (occupancy ${Math.round(r.antam.occupancy * 100)} %): owner nets ~${czk(r.antam.net)} CZK/month (gross ${czk(r.antam.gross)} CZK, platform commission ${czk(r.antam.platformFee)} CZK, Antam Homes 30 % ${czk(r.antam.mgmt)} CZK). Long-term rent benchmark ~${czk(longTermRent)} CZK/month, roughly ${result.withAntamHomes.multipleVsLongTermRent}x (market average ${result.marketAverage.multipleVsLongTermRent}x).`
        }
      ],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-portfolio.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
var apartments = [
  { name: "Secret garden loft", location: "Praha 4", maxGuests: 13, managedSince: "2026-07", note: "new, results after the first season" },
  { name: "Elegant Museum View Apartment (402)", location: "Praha 1", maxGuests: 8, floorAreaM2: 52, ownerMonthlyCzk: 64e3, occupancyPct: 96, period: "12 months to 2026-07" },
  { name: "Modern Museum View Apartment (405)", location: "Praha 1", maxGuests: 8, floorAreaM2: 52, ownerMonthlyCzk: 57e3, occupancyPct: 94, period: "12 months to 2026-07" },
  { name: "Modern AC Apartment", location: "Praha 3", maxGuests: 6, floorAreaM2: 55, ownerMonthlyCzk: 5e4, occupancyPct: 96, period: "2026-02 to 2026-07" },
  { name: "Modern\xED apartm\xE1n se zahradou", location: "Praha 3", maxGuests: 6, floorAreaM2: 60, ownerMonthlyCzk: 42e3, occupancyPct: 85, period: "2026-04 to 2026-07" },
  { name: "Secret garden studio I", location: "Praha 4", maxGuests: 4, managedSince: "2026-07", note: "new, results after the first season" },
  { name: "Secret garden studio II", location: "Praha 4", maxGuests: 4, managedSince: "2026-07", note: "new, results after the first season" },
  { name: "Klement apartment s terasou", location: "Mlad\xE1 Boleslav", maxGuests: 8, floorAreaM2: 85, ownerMonthlyCzk: 3e4, occupancyPct: 91, period: "2026-04 to 2026-07" },
  { name: "Klement apartment", location: "Mlad\xE1 Boleslav", maxGuests: 8, managedSince: "2026-08", note: "new, results after the first season" }
].map((a) => "ownerMonthlyCzk" in a ? { ...a, vsLongTermRent: ratioFor(a.location, a.floorAreaM2, a.ownerMonthlyCzk) ?? void 0 } : a);
var list_portfolio_default = defineTool2({
  name: "list_portfolio",
  title: "List managed apartments",
  description: "List the apartments Antam Homes currently prepares, photographs and manages, with their locations.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: apartments.map((a, i) => {
          const base = `${i + 1}. ${a.name}, ${a.location} (up to ${a.maxGuests} guests)`;
          if ("ownerMonthlyCzk" in a) {
            return `${base}: owner receives ~${a.ownerMonthlyCzk.toLocaleString("en-US")} CZK/month after all fees, occupancy ${a.occupancyPct} % (${a.period})${a.vsLongTermRent ? `, ${a.vsLongTermRent}x long-term rent` : ""}`;
          }
          return `${base}: managed since ${a.managedSince}, ${a.note}`;
        }).join("\n") + "\n\nOwner income = real results recalculated to the current 30 % Antam Homes fee: what the platform actually pays out, minus the cleaning fee; energy paid by owner. Occupancy counts flats managed for more than three months and skips the first 45 days of operation. Long-term rent comes from the Deloitte Rent Index Q2/2026 applied to the flat\u2019s actual floor area. Past results are not a guarantee.\n\nComing soon: the portfolio is expanding to a total of 10 apartments across Prague. Guests have left over 520 reviews across Airbnb and Booking.com."
      }
    ],
    structuredContent: {
      apartments,
      total: apartments.length,
      plannedTotalInPrague: 10,
      guestReviewsTotal: "520+"
    }
  })
});

// src/lib/mcp/tools/get-services.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
var services = [
  { title: "P\u0159\xEDprava bytu a interi\xE9r", description: "Porad\xEDme, co host\xE9 v dan\xE9 lokalit\u011B hledaj\xED: uspo\u0159\xE1d\xE1n\xED, vybaven\xED, drobnosti, kter\xE9 rozhoduj\xED o hodnocen\xED. Bez zbyte\u010Dn\xFDch investic." },
  { title: "Fotky a prezentace", description: "Profesion\xE1ln\xED fotky, popis a nastaven\xED nab\xEDdky tak, aby byt vynikl mezi stovkami dal\u0161\xEDch." },
  { title: "Cenotvorba", description: "Cenu lad\xEDme denn\u011B podle sez\xF3ny, popt\xE1vky, obsazenosti a okol\xED, ne jedna cena na cel\xFD rok." },
  { title: "Host\xE9 a komunikace", description: "Odpov\u011Bdi do minut, informace k p\u0159\xEDjezdu, podpora b\u011Bhem pobytu a rychl\xE9 \u0159e\u0161en\xED situac\xED." },
  { title: "\xDAklid, kontrola a \xFAdr\u017Eba", description: "Po ka\u017Ed\xE9m pobytu \xFAklid a kontrola stavu, drobn\xE9 opravy hned, \u0159emesln\xEDci, kdy\u017E je pot\u0159eba." },
  { title: "M\u011Bs\xED\u010Dn\xED p\u0159ehled", description: "Jasn\xFD p\u0159ehled rezervac\xED, v\xFDnos\u016F, n\xE1klad\u016F a toho, co se v byt\u011B \u0159e\u0161ilo, na jednu stranu." }
];
var faq = [
  { question: "Mus\xED b\xFDt byt u\u017E p\u0159ipraven\xFD?", answer: "Ne. Um\xEDme se pod\xEDvat i na byt p\u0159ed spu\u0161t\u011Bn\xEDm a \u0159\xEDct, co d\xE1v\xE1 smysl p\u0159ipravit." },
  { question: "Kolik je pot\u0159eba investovat do p\u0159\xEDpravy nemovitosti?", answer: "Z\xE1le\u017E\xED na stavu a vybaven\xED bytu. Uveden\xED do provozu stoj\xED 25 000 K\u010D: p\u0159\xEDprava bytu a nab\xEDdek, focen\xED, nastaven\xED cen a spu\u0161t\u011Bn\xED prodeje. Vybaven\xED se kupuje za po\u0159izovac\xED ceny s doklady, bez p\u0159ir\xE1\u017Eky; u projekt\u016F nad 30 000 K\u010D \xFA\u010Dtuje Antam Homes 20 % z rozpo\u010Dtu za \u0159\xEDzen\xED. U \xFApln\u011B pr\xE1zdn\xE9ho bytu po\u010D\xEDtejte orienta\u010Dn\u011B kolem 100 000 K\u010D na jeden pokoj; vybaven\xED z\u016Fst\xE1v\xE1 majitele." },
  { question: "M\u016F\u017Eu byt n\u011Bkdy vyu\u017E\xEDt pro sebe?", answer: "Byt si m\u016F\u017Eete kdykoli blokovat pro sebe nebo rodinu. U nejvyt\xED\u017Een\u011Bj\u0161\xEDch sv\xE1tk\u016F, jako jsou V\xE1noce, Silvestr a Velikonoce, se na term\xEDnu nejd\u0159\xEDv domluv\xEDme. U\u017E potvrzen\xE9 rezervace host\u016F z\u016Fst\xE1vaj\xED nedot\u010Den\xE9. Prvn\xEDch 14 noc\xED v roce je bez odm\u011Bny Antam Homes, majitel plat\xED jen \xFAklid; garantovan\xE1 ro\u010Dn\xED \u010D\xE1stka se za blokovan\xE9 noci pom\u011Brn\u011B sni\u017Euje, v\u010Detn\u011B t\u011Bchto 14." },
  { question: "Jak budu v\u011Bd\u011Bt, co byt vyd\u011Bl\xE1v\xE1?", answer: "Ka\u017Ed\xFD m\u011Bs\xEDc zp\u011Btn\u011B p\u0159ehled na jednu stranu: obsazen\xE9 noci, v\xFDnos z jednotliv\xFDch platforem, provize platforem, odm\u011Bna 30 % a co se v byt\u011B \u0159e\u0161ilo, spolu s fakturou na odm\u011Bnu. Vy\xFA\u010Dtov\xE1n\xED i v\xFDplata prob\u011Bhnou do 15. dne n\xE1sleduj\xEDc\xEDho m\u011Bs\xEDce." },
  { question: "Kolik spr\xE1va stoj\xED?", answer: "Na\u0161e odm\u011Bna je 30 % z \u010Dist\xE9ho v\xFDnosu: z toho, co p\u0159ijde od Airbnb a Booking.com, po ode\u010Dten\xED \xFAklidov\xE9ho poplatku. Je kone\u010Dn\xE1, nic dal\u0161\xEDho se nep\u0159i\u010D\xEDt\xE1, bez fixn\xEDch ani m\u011Bs\xED\u010Dn\xEDch poplatk\u016F, a je v n\xED i garance v\xFDnosu. Pokr\xFDv\xE1 tak\xE9 DPH z provize platformy, internet, hygienick\xE9 pot\u0159eby pro hosty a \u010Distic\xED prost\u0159edky. Drobn\xE9 opravy do 5 000 K\u010D vy\u0159\xEDd\xEDme sami a n\xE1klady strhneme z v\xFDnosu, dohromady nejv\xFD\u0161e 20 000 K\u010D za rok; v\u011Bt\u0161\xED opravy nejd\u0159\xEDv nahl\xE1s\xEDme majiteli." },
  { question: "Co je Garance v\xFDnosu?", answer: "Ke ka\u017Ed\xE9mu bytu, kter\xFD Antam Homes vezme do spr\xE1vy, dostane majitel p\xEDsemn\xE9 ro\u010Dn\xED minimum: n\xE1jem, kter\xFD by byt vyd\u011Blal dlouhodob\u011B, plus energie. Kdy\u017E v\xFDnos za 12 m\u011Bs\xEDc\u016F z\u016Fstane pod minimem, rozd\xEDl se dorovn\xE1 z odm\u011Bn Antam Homes, nebo m\u016F\u017Ee majitel okam\u017Eit\u011B odej\xEDt; volba je jeho. Zp\u016Fsobilost bytu se ov\u011B\u0159uje zdarma p\u0159edem a byt, kter\xFD garanci neunese, Antam Homes do spr\xE1vy nevezme." },
  { question: "Kdo plat\xED \xFAklid a energie?", answer: "Host plat\xED vedle ceny za ubytov\xE1n\xED i \xFAklidov\xFD poplatek; ten pokr\xFDv\xE1 \xFAklid a pr\xE1dlo a z\u016Fst\xE1v\xE1 cel\xFD Antam Homes, tak\u017Ee se z v\xFDnosu majitele na \xFAklid nic nestrh\xE1v\xE1 (ve vy\xFA\u010Dtov\xE1n\xED je samostatnou polo\u017Ekou). V\xFDnos, kter\xFD se d\u011Bl\xED 70/30, je to, co p\u0159ijde od platformy, po ode\u010Dten\xED \xFAklidov\xE9ho poplatku. Energie (elekt\u0159ina, voda) hrad\xED majitel." },
  { question: "Kdo plat\xED DPH z provize platformy?", answer: "Antam Homes, ze sv\xE9 odm\u011Bny. Airbnb a Booking.com fakturuj\xED provizi ze zahrani\u010D\xED a \u010Desk\xE1 DPH z n\xED se odv\xE1d\xED u n\xE1s; do v\xFDnosu majitele nevstupuje a z jeho pod\xEDlu se nestrh\xE1v\xE1." },
  { question: "Jak dlouho spolupr\xE1ce trv\xE1 a jak ji ukon\u010D\xEDm?", answer: "Smlouva se uzav\xEDr\xE1 na 12 m\u011Bs\xEDc\u016F. Po nich pokra\u010Duje na dobu neur\u010Ditou a lze ji kdykoli ukon\u010Dit s v\xFDpov\u011Bdn\xED lh\u016Ftou 4 m\u011Bs\xEDce. Potvrzen\xE9 rezervace se b\u011Bhem v\xFDpov\u011Bdn\xED lh\u016Fty v\u017Edy dokon\u010D\xED." },
  { question: "Je \u010D\xE1stka v kalkula\u010Dce p\u0159ed, nebo po provizi?", answer: "Po. V\u0161e ozna\u010Den\xE9 jako v\xFDnos pro majitele je u\u017E po ode\u010Dten\xED provize platformy i odm\u011Bny 30 %. Odm\u011Bna je kone\u010Dn\xE1; energie hrad\xED majitel zvl\xE1\u0161\u0165." },
  { question: "Jak\xE9 povinnosti kr\xE1tkodob\xFD pron\xE1jem p\u0159in\xE1\u0161\xED a kdo je \u0159e\u0161\xED?", answer: "Evidence host\u016F, hl\xE1\u0161en\xED zahrani\u010Dn\xEDch host\u016F cizineck\xE9 policii, m\xEDstn\xED poplatek z pobytu a registrace v e-Turista, provozn\xED povinnosti kolem host\u016F \u0159e\u0161\xED Antam Homes. Zdan\u011Bn\xED p\u0159\xEDjmu z pron\xE1jmu z\u016Fst\xE1v\xE1 na majiteli; podklady dostane." },
  { question: "Co kdy\u017E host n\u011Bco poni\u010D\xED?", answer: "Byt se kontroluje po ka\u017Ed\xE9m pobytu. \u0160koda se zdokumentuje a nejd\u0159\xEDv vym\xE1h\xE1 po hostovi a p\u0159es platformu (Airbnb AirCover, \u0159e\u0161en\xED \u0161kod Booking.com). Co se tam nepoda\u0159\xED z\xEDskat, hrad\xED Antam Homes do ro\u010Dn\xEDho limitu podle velikosti bytu: 5 000 K\u010D u 1+kk, 10 000 K\u010D u 2+kk, 15 000 K\u010D u 3+kk, 20 000 K\u010D u 4+kk a 25 000 K\u010D u v\u011Bt\u0161\xEDch. Majitel se dozv\xED hned, v\u010Detn\u011B fotek. Kryt\xED se t\xFDk\xE1 \u0161kod zp\u016Fsoben\xFDch hostem; opot\u0159eben\xED, poruchy z v\u011Bku a z\xE1vady v dom\u011B jsou opravy a \xFAdr\u017Eba a z\u016Fst\xE1vaj\xED na majiteli (drobn\xE9 do 5 000 K\u010D se \u0159e\u0161\xED hned a strh\xE1vaj\xED z v\xFDnosu, nejv\xFD\u0161e 20 000 K\u010D za rok, v\u011Bt\u0161\xED po jeho souhlasu)." },
  { question: "Co na to soused\xE9 a SVJ?", answer: "Host\xE9 dost\xE1vaj\xED pravidla domu p\u0159edem, byt m\xE1 danou kapacitu (\u017E\xE1dn\xE9 party) a soused\xE9 maj\xED kontakt. Pokud stanovy SVJ kr\xE1tkodob\xE9 ubytov\xE1n\xED v\xFDslovn\u011B zakazuj\xED, Antam Homes to majiteli \u0159ekne p\u0159ed podpisem." },
  { question: "Pro\u010D to ned\u011Blat s\xE1m p\u0159es Airbnb?", answer: "M\u016F\u017Eete, n\u011Bkte\u0159\xED majitel\xE9 to zvl\xE1daj\xED. Je to ale pr\xE1ce na ka\u017Ed\xFD den: odpov\xEDdat host\u016Fm do minut, hl\xEDdat ceny podle popt\xE1vky, \u0159e\u0161it \xFAklid a kl\xED\u010De a dr\u017Eet krok s t\xEDm, co Airbnb a Booking m\u011Bn\xED (algoritmy, pravidla, poplatky, povinnosti). Antam Homes to d\u011Bl\xE1 denn\u011B pro v\xEDc byt\u016F najednou." },
  { question: "Pracujete i s jin\xFDmi platformami nebo firmami?", answer: "Byty se inzeruj\xED tam, kde je v Praze re\xE1ln\xE1 popt\xE1vka: p\u0159edev\u0161\xEDm Airbnb a Booking.com, kter\xE9 Antam Homes zn\xE1 do detailu (algoritmy, pravidla, zm\u011Bny). Dal\u0161\xED platformy se p\u0159id\xE1vaj\xED jen tam, kde bytu p\u0159inesou rezervace nav\xEDc. Provoz nejde p\u0159es prost\u0159edn\xEDky: hosty, ceny, \xFAklid i kontrolu bytu \u0159e\u0161\xED vlastn\xED t\xFDm, extern\xED jsou jen \u0159emesln\xEDci." },
  { question: "Pro koho kr\xE1tkodob\xFD pron\xE1jem ned\xE1v\xE1 smysl?", answer: "Kdy\u017E SVJ ubytov\xE1n\xED zakazuje nebo to soused\xE9 necht\u011Bj\xED; kdy\u017E majitel pot\u0159ebuje ka\u017Ed\xFD m\u011Bs\xEDc stejnou \u010D\xE1stku; kdy\u017E chce byt v\u011Bt\u0161inu roku pou\u017E\xEDvat s\xE1m; kdy\u017E je byt ve stavu, do kter\xE9ho nechce nic d\xE1t. Lokalita mimo centrum ani star\u0161\xED d\u016Fm probl\xE9m nejsou." }
];
var get_services_default = defineTool3({
  name: "get_services_and_faq",
  title: "Get services and FAQ",
  description: "Get what Antam Homes does for apartment owners (full short-term rental management) plus the frequently asked questions and answers from the website.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: [
          "Services:",
          ...services.map((s) => `- ${s.title}: ${s.description}`),
          "",
          "FAQ:",
          ...faq.map((f) => `Q: ${f.question}
A: ${f.answer}`)
        ].join("\n")
      }
    ],
    structuredContent: {
      services,
      faq,
      managementCommissionRate: 0.3,
      commissionBase: "net revenue = what the platform pays out for accommodation, without the cleaning fee, after deducting the Airbnb/Booking.com commission. The Czech VAT on that commission is paid by Antam Homes out of its own fee and is not deducted from the owner's share.",
      ownerContract: {
        initialTermMonths: 12,
        thenIndefinite: true,
        noticePeriodMonths: 4
      },
      guestDamageCover: {
        description: "Qualifying smaller guest-caused damage is first claimed from the guest and through the platform. What is not recovered there is covered by Antam Homes up to a yearly per-apartment limit. Wear and tear, age-related failures and building faults are repairs and stay with the owner.",
        yearlyLimitPerRoomCzk: DAMAGE_COVER_PER_ROOM,
        yearlyLimitMaxCzk: DAMAGE_COVER_MAX,
        yearlyLimitByLayoutCzk: {
          ...Object.fromEntries(Object.entries(ROOMS).map(([k, rooms]) => [k, annualDamageCover(rooms)])),
          "5kk+": DAMAGE_COVER_MAX
        }
      }
    }
  })
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
var get_contact_default = defineTool4({
  name: "get_contact_info",
  title: "Get contact information",
  description: "Get Antam Homes contact details and how an apartment owner can start a no-obligation conversation about their apartment.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      company: "Donut Point, s.r.o.",
      companyId: "21904022",
      registeredSeat: "P\u0159\xED\u010Dn\xE1 1892/4, Nov\xE9 M\u011Bsto, 110 00 Praha 1",
      brand: "Antam Homes",
      email: "antamhomes@gmail.com",
      phone: "727 952 459",
      officePhone: "607 338 126",
      website: "https://www.antamhomes.com",
      vietnameseVersion: "https://www.antamhomes.com/vn",
      serviceArea: "Praha a okol\xED",
      languages: ["\u010De\u0161tina", "Ti\u1EBFng Vi\u1EC7t"]
    };
    return {
      content: [
        {
          type: "text",
          text: `Antam Homes (Donut Point, s.r.o., I\u010CO 21904022)
Email: ${info.email}
Telefon: ${info.phone}
Kancel\xE1\u0159: ${info.officePhone}
Web: ${info.website} (Vietnamese: ${info.vietnameseVersion})
Oblast: ${info.serviceArea}`
        }
      ],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "antamhome",
  title: "Antamhome",
  version: "0.1.0",
  instructions: "Tools for Antam Homes, a short-term rental (Airbnb/Booking) management company for apartment owners in Prague. Use `estimate_rental_yield` to estimate an owner's monthly net income for a given Prague district and apartment size, `list_portfolio` for the apartments under management, `get_services_and_faq` for what the company does, and `get_contact_info` for contact details. All data is public marketing information.",
  tools: [estimate_yield_default, list_portfolio_default, get_services_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
